#+title: DROID metapatch
#+options: toc:nil

* Introduction
The DROID metapatch library aims to create an easier and more pythonic way of creating DROID patch generators.
DROID patch generators are a recent feature added to the the DROID Forge application that allows you to define python scripts that generate full-fledges patches.

DROID is a series of eurorack controllers and CV processors made by [[https://shop.dermannmitdermaschine.de/][Der Mann mit der Maschine]].

* Comparison to the bundled =pg.py= script
This library is quite a bit more advanced than the bundled =pg.py= script. It's not meant to be more difficult though, but instead it should remove some of the complicated elements of writing patch generators. For example:

+ It automatically collects the input parameters
+ It ensures that correct output types for Forge to pick up, such as the JSON synopsis out, the parameter types and presets.
+ It has a complete library of all the DROID circuits, so if you have a modern editor, you get auto-completion of DROID circuits, and a context-specific help from the DROID manual.
+ You can convert DROID patches into partial patch generators through a script, so it should be super fast to get started.


* Installation
** Installing the library

Before you can write a patch generator, please install this library to your system python environment.
Forge does not support virtual environments, so you must install this library
somewhere where your default python library can find it.

This library is available from pypi, use =pip install droid-metapatch= to install it.

** Installation on MacOS
DROID Forge uses the version of python that is bundled with MacOS. If you have installed python via homebrew or any other way, you may have multiple different python versions available.

There are several ways to solve this:

*** Install the library with the system Python
To ensure install this library to the one bundled with MacOS, run the following command:

#+begin_example
$ /usr/bin/python3 -m pip install droid-metapatch
#+end_example

Note that this may result in a situation where the Forge has this library available, but your editor or shell does not.
In that case, you can run the =pip install droid-metapatch= also. You will then have two copies installed, one for each environment.

*** Installing the metapatch library by hand
You could also clone or download this repository, and place the =metapatch= folder into your Generators folder (located in your home directory under the =DROID Patches= folder.)

This should work, but note that the =droid-metapatch= CLI utility will not be available then.

* How to use the metapatch library
#+INCLUDE: docs/getting-started.org

* Getting help
If you have any problems with the library, let me know on the DROID discord server. I'm known as eising on that server.

Please note that any support will be on a best effort basis, if I have the time an energy.

If you have found a bug, please create an issue here on github.
